### ISSUE TITLE
Using both your gem and default simple_form

### ISSUE THREAD

**Issue by jeremybdk** [abevoelker/simple_form_tailwind#3]
Hello,
We're in the process of rewriting our frontend with tailwind, and are looking to migrate current pages one by one.

If I setup your gem, it breaks some of our current simple_form implementation that we have. Do you think it would be possible to keep the existing simple form behaviour while adding a tailwind theme/behaviour to other one?

I would love to be able to get my old and new forms to work at the same time,

Thanks in advance,

Jeremy

**Comment by abevoelker** [comment]
I think it should be possible - you'll just need different wrappers and wrapper mappings defined in your `simple_form.rb` initializer. You could try [copying from this gem's generator](https://github.com/abevoelker/simple_form_tailwind_css/blob/2c6e7d3654bc2f5dc1bf43db4618f968ce874502/lib/generators/simple_form/tailwind/templates/simple_form.rb) and renaming things. Then you can tell SimpleForm to use them with the `:wrapper` and/or `:as` options on each form input (`f.input`)

**Comment by jeremybdk** [comment]
Thanks for your help, I ended up replacing all my forms so that they use your gem!

**Comment by abevoelker** [comment]
Glad you were able to use the gem - please continue adding issues and/or PRs if you find any more improvements! :tada:
