### ISSUE TITLE
Overriding default error_notification classes globally

### ISSUE THREAD

**Issue by philipithomas** [abevoelker/simple_form_tailwind#8]
I see in this file that it's possible to override the default error notification classes:

https://github.com/abevoelker/simple_form_tailwind_css/blob/master/lib/simple_form/tailwind/error_notification.rb#L13

But, I'm having trouble doing this through the `simple_form.rb` config file.  Is it supported to do a universal override of the error classes via the config?

**Comment by abevoelker** [comment]
It's a bit hazy but IIRC the `@options` instance variable there is only populated by what's passed directly to the `<%= f.error_notification`. What you may be able to do instead is either make your own form builder, or monkey patch mine to default the options to what you want instead. E.g.

```ruby
class YourApp::FormBuilder < SimpleForm::Tailwind::FormBuilder
  def error_notification(options = {})
    # Your logic here to set options from your config or whatever:
    options = { class: 'your-error-notification-class' }.merge(options)

    SimpleForm::Tailwind::ErrorNotification.new(self, options).render # or `super`
  end
end
```
```erb
<%= simple_form_for(@foo, builder: YourApp::FormBuilder, html: { class: "space-y-6" }) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
<% end %>
```

**Comment by philipithomas** [comment]
Thanks for the kind and helpful response @abevoelker. I'll try this out. 

And, thanks for making + maintaining this gem!
